name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: SPID.AspNetCore.Authentication
    - name: Build
      run: dotnet build --no-restore
      working-directory: SPID.AspNetCore.Authentication
    - name: Test with spid-sp-test
      working-directory: SPID.AspNetCore.WebApp
      run: |
        sudo apt-get update && sudo apt-get install xmlsec1
        sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl xmlsec1 python3-pip
        dotnet bin/Debug/net5.0/SPID.AspNetCore.WebApp.dll &
        spid_sp_test --metadata-url https://localhost:5001/spid/metadata.xml --authn-url https://localhost:5001/home/login?idpname=SpidSpTest --extra --debug ERROR --profile spid-sp-ag-public-full
