name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: SPID.AspNetCore.Authentication
    - name: Build
      run: dotnet build --no-restore
      working-directory: SPID.AspNetCore.Authentication
    - name: Update apt repo
      run: sudo apt update
    - name: Install dependencies
      run: sudo apt install -y libxml2-dev libxmlsec1-dev libxmlsec1-openssl xmlsec1 python3-pip
    - name: Install spid-sp-test
      run: sudo pip install spid-sp-test --upgrade --no-cache
    - name: Run SPID.AspNetCore.WebApp
      working-directory: SPID.AspNetCore.Authentication/SPID.AspNetCore.WebApp
      run: dotnet bin/Debug/net5.0/SPID.AspNetCore.WebApp.dll &
    - name: Test with spid-sp-test
      run: spid_sp_test --metadata-url https://localhost:5001/spid/metadata.xml --authn-url https://localhost:5001/home/login?idpname=SpidSpTest --extra --debug ERROR --profile spid-sp-ag-public-full -tr
